spring:
    application:
        name: project1

    datasource:
        url: jdbc:mysql://localhost:3306/sport_ecommerce
        username: root
        password: 123456

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none

    mail:
        host: smtp.gmail.com
        port: 465
        username: vietddls06@gmail.com
        password: loeavfbmttsgqnlu
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 50MB

api:
    prefix: /api/v1

server:
    port: 8080

jwt:
    signerKey: 8o24T1lHAIsiyuoKMPYnVaavjaVWmTbAE4tofn0jmEs=
    valid-duration: 7200 # in seconds 2h
    refreshable-duration: 72000 # in seconds


app:
    minio:
        host: "http://localhost:9000/"
        local: "http://localhost:9000/"
        accessKey: "minioadmin"
        secretKey: "minioadmin"
        bucketName: "sports"
    image:
        folder:
            category: "D:\\Downloads\\image\\category\\"
            brand: "D:\\Downloads\\image\\brand\\"
            product: "D:\\Downloads\\image\\product\\"
        keyName:
            category: "category/"
            brand: "brand/"
            product: "product/"

vnpay:
    pay-url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
    return-url: "${VNPAY_RETURN_URI:http://127.0.0.1:5501/sport-econmmer/fronend/sport/front-end/order-success.html}"
    tmn-code: "VFVK4LS2" #tmn code
    secret-key: "7FCMYIFHA0YB62ELDJ78WKMXJS9I2EXP" # key code
    api-url: "https://sandbox.vnpayment.vn/merchant_webapi/api/transaction"