spring:
    application:
        name: project1

    datasource:
        url: jdbc:mysql://localhost:3306/project1
        username: root
        password: 123456

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update

server:
    port: 8080

jwt:
    signerKey: 8o24T1lHAIsiyuoKMPYnVaavjaVWmTbAE4tofn0jmEs=
    valid-duration: 7200 # in seconds 2h
    refreshable-duration: 72000 # in seconds
